-- Run this in your Supabase SQL Editor to update the mobile number constraint without losing data:

-- 1. Drop the old unique constraint if it exists (it might have an autogenerated name like `customers_business_id_mobile_key`)
ALTER TABLE public.customers DROP CONSTRAINT IF EXISTS customers_business_id_mobile_key;

-- 2. Create a new unique index that only applies when the mobile number is not empty
CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_unique_mobile 
  ON public.customers(business_id, mobile) 
  WHERE mobile != '';
